server:
  port: 8086
  servlet:
    context-path: /nice-mall-backend

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nice_mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tian787604

  redis:
    host: 127.0.0.1
    port: 6379
    password: tian2189543
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml


shiro:
  #后端免认证url
  anonUrl: /nice-mall-backend/login/**,/nice-mall-backend/register,/nice-mall-backend/register/verifycode,/nice-mall-backend//addcommdity
  #token有效期，单位秒
  jwtTimeOut: 43200

#开启驼峰命名匹配规则
mybatis:
  configuration:
    map-underscore-to-camel-case: true

debug: true

