server:
  port: 8086
  servlet:
    context-path: /nice-mall-backend

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nice_mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tian787604

  redis:
    host: 127.0.0.1
    port: 6379
    password: tian2189543
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml


shiro:
  #后端免认证url
  anonUrl: /nice-mall-backend/login/**,/nice-mall-backend/register,/nice-mall-backend/register/verifycode
  #token有效期，单位秒
  jwtTimeOut: 300

#开启驼峰命名匹配规则
mybatis:
  configuration:
    map-underscore-to-camel-case: true

debug: true

# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: ybfq # 访问身份验证中用到用户标识
    accessKeySecret: qwertyuiop # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: nice-mall-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀


