server:
  port: 8086
  servlet:
    context-path: /nice-mall-backend

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nice_mall?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: tian787604

  redis:
    host: 127.0.0.1
    port: 6379
    password: tian2189543
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

  #开启p6spy打印功能
  dynamic:
    p6spy: true


#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml


shiro:
  #后端免认证url
  anonUrl: /nice-mall-backend/login/**,/nice-mall-backend/register,/nice-mall-backend/register/verifycode,/nice-mall-backend/home/**,/nice-mall-backend/self/**,/nice-mall-backend/personal/change
  #token有效期，单位秒
  jwtTimeOut: 86400

#开启驼峰命名匹配规则
mybatis:
  configuration:
    map-underscore-to-camel-case: true

debug: true

nice:
  worker:
    workerId: 1
    datacenterId: 1