spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: tian2189543
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0